trigger:
- main  # or your specific branch

variables:
  # Docker Hub credentials
  DOCKER_REGISTRY_SERVICE_CONNECTION: dockerhub
  IMAGE_NAME: sadiksa/innerapi
  DOCKERFILE_PATH: InnerApi/Dockerfile  # Path to your Dockerfile

stages:
- stage: BuildAndPush
  jobs:
  - job: Build
    displayName: Build and Push Docker Image
    pool:
      name: buildernew

    steps:
    - task: Docker@2
      inputs:
        containerRegistry: '$(DOCKER_REGISTRY_SERVICE_CONNECTION)'
        repository: '$(IMAGE_NAME)'
        command: 'buildAndPush'
        Dockerfile: '$(DOCKERFILE_PATH)'
        tags: |
          $(Build.BuildNumber)
      
    - task: PublishBuildArtifacts@1
      displayName: 'Publish deployment artifacts'
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/InnerApi/K8s-files/'
        ArtifactName: 'k8s-ymls-for-innerapi'
        publishLocation: 'Container'
        targetPath: |
          Roles/godmoderole.yml
          Roles/godmodeserviceaccount.yml
          Roles/godmoderolebinding.yml
          Roles/godmodeclusterrole.yml
          Roles/godmodeclusterrolebinding.yml
          App/innerapideployment.yml
          App/innerapisvc.yml
          App/innerapiingress.yml
