apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: god-role-binding
  namespace: innerapi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: god-role
subjects:
- kind: ServiceAccount
  name: god
  namespace: innerapi
